### ISSUE TITLE
End Of Stream

### ISSUE THREAD

**Issue by Glitched4Life** [A-Random-Person-on-Github/Eaglercraft-Shaders-Update-HTML-FILES#2]
So when I join a server and I will leave a video example, It kicks me with the error End Of Stream but If I join another server It does NOT kick me... The server runs on repl and I just wanna know why it keeps kicking me :( Please get back to me as soon as possible! Thanks!

[](url)

**Comment by A-Random-Person-on-Github** [comment]
what server did u try to connect to

**Comment by Glitched4Life** [comment]
[https://res.cdn.office.net/assets/mail/file-icon/png/video_16x16.png]End Of Stream Error.mp4<https://1drv.ms/v/s!Akp0pe-BF5PJgVPdSE0fNqT2c1gp>


Here we go
________________________________

**Comment by Glitched4Life** [comment]
I can host a zoom if you would like so you an help with this issue...

**Comment by A-Random-Person-on-Github** [comment]
are you using the web demo or the html file

**Comment by A-Random-Person-on-Github** [comment]
i recomend use the html file se

**Comment by Glitched4Life** [comment]
I am uzing the international html file
________________________________

**Comment by A-Random-Person-on-Github** [comment]
Usebthe other pne
